version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/data/mysql

volumes:
  mysql_data:
